version: "3.7"
services:
 mysql:
  container_name: mysql
  image: mysql:8.0.33
  volumes:
     - ./sql-data/db:/var/lib/mysql
  ports:
     - "3306:3306"
  hostname: mysqlprueba
  environment: 
     MYSQL_DATABASE: "PruebaDB"
     MYSQL_USER: "admin"
     MYSQL_PASSWORD: "admin"
     MYSQL_ROOT_PASSWORD: "root"